/* tslint:disable */
/* eslint-disable */
/**
 * Template - Backend
 * Essa API descreve as operações do sistema do Liga de Algoritmos.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

