/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as RankingIndexRouteImport } from './routes/ranking/index'
import { Route as ProblemasIndexRouteImport } from './routes/problemas/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HistoriaIndexRouteImport } from './routes/historia/index'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as ProblemasProblemIdRouteImport } from './routes/problemas/$problemId'
import { Route as AuthenticatedProfileRouteImport } from './routes/authenticated/profile'
import { Route as AuthenticatedIntegrantesRouteImport } from './routes/authenticated/integrantes'
import { Route as AuthenticatedAdminRouteImport } from './routes/authenticated/admin'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemasIndexRoute = ProblemasIndexRouteImport.update({
  id: '/problemas/',
  path: '/problemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaIndexRoute = HistoriaIndexRouteImport.update({
  id: '/historia/',
  path: '/historia/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemasProblemIdRoute = ProblemasProblemIdRouteImport.update({
  id: '/problemas/$problemId',
  path: '/problemas/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrantesRoute =
  AuthenticatedIntegrantesRouteImport.update({
    id: '/integrantes',
    path: '/integrantes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/authenticated/admin': typeof AuthenticatedAdminRoute
  '/authenticated/integrantes': typeof AuthenticatedIntegrantesRoute
  '/authenticated/profile': typeof AuthenticatedProfileRoute
  '/problemas/$problemId': typeof ProblemasProblemIdRoute
  '/': typeof HomeIndexRoute
  '/historia/': typeof HistoriaIndexRoute
  '/login/': typeof LoginIndexRoute
  '/problemas/': typeof ProblemasIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/authenticated/admin': typeof AuthenticatedAdminRoute
  '/authenticated/integrantes': typeof AuthenticatedIntegrantesRoute
  '/authenticated/profile': typeof AuthenticatedProfileRoute
  '/problemas/$problemId': typeof ProblemasProblemIdRoute
  '/': typeof HomeIndexRoute
  '/historia': typeof HistoriaIndexRoute
  '/login': typeof LoginIndexRoute
  '/problemas': typeof ProblemasIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/authenticated/admin': typeof AuthenticatedAdminRoute
  '/authenticated/integrantes': typeof AuthenticatedIntegrantesRoute
  '/authenticated/profile': typeof AuthenticatedProfileRoute
  '/problemas/$problemId': typeof ProblemasProblemIdRoute
  '/_home/': typeof HomeIndexRoute
  '/historia/': typeof HistoriaIndexRoute
  '/login/': typeof LoginIndexRoute
  '/problemas/': typeof ProblemasIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/authenticated'
    | '/authenticated/admin'
    | '/authenticated/integrantes'
    | '/authenticated/profile'
    | '/problemas/$problemId'
    | '/'
    | '/historia/'
    | '/login/'
    | '/problemas/'
    | '/ranking/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/authenticated'
    | '/authenticated/admin'
    | '/authenticated/integrantes'
    | '/authenticated/profile'
    | '/problemas/$problemId'
    | '/'
    | '/historia'
    | '/login'
    | '/problemas'
    | '/ranking'
    | '/signup'
  id:
    | '__root__'
    | '/authenticated'
    | '/authenticated/admin'
    | '/authenticated/integrantes'
    | '/authenticated/profile'
    | '/problemas/$problemId'
    | '/_home/'
    | '/historia/'
    | '/login/'
    | '/problemas/'
    | '/ranking/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ProblemasProblemIdRoute: typeof ProblemasProblemIdRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HistoriaIndexRoute: typeof HistoriaIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProblemasIndexRoute: typeof ProblemasIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problemas/': {
      id: '/problemas/'
      path: '/problemas'
      fullPath: '/problemas/'
      preLoaderRoute: typeof ProblemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia/': {
      id: '/historia/'
      path: '/historia'
      fullPath: '/historia/'
      preLoaderRoute: typeof HistoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problemas/$problemId': {
      id: '/problemas/$problemId'
      path: '/problemas/$problemId'
      fullPath: '/problemas/$problemId'
      preLoaderRoute: typeof ProblemasProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/profile': {
      id: '/authenticated/profile'
      path: '/profile'
      fullPath: '/authenticated/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/integrantes': {
      id: '/authenticated/integrantes'
      path: '/integrantes'
      fullPath: '/authenticated/integrantes'
      preLoaderRoute: typeof AuthenticatedIntegrantesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/admin': {
      id: '/authenticated/admin'
      path: '/admin'
      fullPath: '/authenticated/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedIntegrantesRoute: typeof AuthenticatedIntegrantesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedIntegrantesRoute: AuthenticatedIntegrantesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ProblemasProblemIdRoute: ProblemasProblemIdRoute,
  HomeIndexRoute: HomeIndexRoute,
  HistoriaIndexRoute: HistoriaIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProblemasIndexRoute: ProblemasIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
